### ISSUE TITLE
Why std::map instead of std::unordered_map?

### ISSUE THREAD

**Issue by phcerdan** [lohedges/aabbcc#16]
`std::map` is ordered, is the code taking advantage of it?
If not, `std::unordered_map` should be faster for every operation.

**Comment by lohedges** [comment]
Thanks for this. I added the `std::map` map to fix a previous issue and thought at the time that ordering might be useful for some other features that I had planned on adding. I've now switched to `std::unordered_map` for the speed benefits it provides.

**Comment by lohedges** [comment]
Hmmm, `std::unordered_map` appears to not be consistently supported across the range of compilers that we test against, regardless of using `-std=c++11`, or `-std=gnu++11`, or `-std=c++0x`. I know that some people use older compilers, so I'll revert for now so that the build works again.

**Comment by lohedges** [comment]
Actually, I also needed the additional compiler flags when building the Python wrapper. (Not sure why it only failed to work with `std::unordered_map`) I thought I had these in the `setup.py`, but perhaps they got removed for some other reason. Anyway, the build is working now.
