### ISSUE TITLE
Compute the cost  why Multiply 2？

### ISSUE THREAD

**Issue by bellpo** [lohedges/aabbcc#17]
Compute the cost why Multiply 2？

// Cost of creating a new parent for this node and the new leaf.
double cost = 2.0 * combinedSurfaceArea; 

 // Minimum cost of pushing the leaf further down the tree.
double inheritanceCost = 2.0 * (combinedSurfaceArea - surfaceArea);   

but hree (  aabb.getSurfaceArea()   ) not Multiply 2？
 if (nodes[left].isLeaf())
 {
        AABB aabb;
        aabb.merge(leafAABB, nodes[left].aabb);
        costLeft = aabb.getSurfaceArea() + inheritanceCost;
 }
else
 {
         AABB aabb;
         aabb.merge(leafAABB, nodes[left].aabb);
         double oldArea = nodes[left].aabb.getSurfaceArea();
         double newArea = aabb.getSurfaceArea();
         costLeft = (newArea - oldArea) + inheritanceCost;
}

**Comment by lohedges** [comment]
I must admit that I don't quite understand your question, particularly the "but three... Not Multiply 2" part. This code was adapted from the [box2d](https://github.com/erincatto/box2d) library, and uses the same approach for estimating the cost of pushing nodes down the tree when rebalancing. You can see effectively the same thing [here](https://github.com/erincatto/box2d/blob/master/src/collision/b2_dynamic_tree.cpp#L224).

**Comment by bellpo** [comment]
> I must admit that I don't quite understand your question, particularly the "but three... Not Multiply 2" part. This code was adapted from the [box2d](https://github.com/erincatto/box2d) library, and uses the same approach for estimating the cost of pushing nodes down the tree when rebalancing. You can see effectively the same thing [here](https://github.com/erincatto/box2d/blob/master/src/collision/b2_dynamic_tree.cpp#L224).
Im sorry,my english level is bad. 

Thanks Your Anwser, I think about this question so hard.  but i cant understand it. if you know,i will so happy. lol.

// Cost of creating a new parent for this node and the new leaf.
double cost = 2.0 * combinedSurfaceArea; 

here  why multiply 2 ?  because here only add combinedSurfaceArea oncetime for add new node.


And I think here should be
{

        // Cost of creating a new parent for this node and the new leaf.
        double cost =  combinedSurfaceArea;

        // Minimum cost of pushing the leaf further down the tree.
        double inheritanceCost =  (combinedSurfaceArea - surfaceArea);

        // Cost of descending to the left.
        double costLeft;
        if (nodes[left].isLeaf())
        {
            AABB aabb;
            aabb.merge(leafAABB, nodes[left].aabb);
            costLeft = aabb.getSurfaceArea() + inheritanceCost;
        }
        else
        {
            AABB aabb;
            aabb.merge(leafAABB, nodes[left].aabb);
            double oldArea = nodes[left].aabb.getSurfaceArea();
            double newArea = aabb.getSurfaceArea();
            costLeft = (newArea - oldArea) + inheritanceCost;
        }
} 

so compare cost and costLeft ,  can get the smallest Bounding box for all tree .

**Comment by lohedges** [comment]
Hi again. As mentioned, I followed the approach from [box2d](https://github.com/erincatto/box2d). I'm not 100% sure why the factor of 2 appears, but it is present in their code too. A great explanation of Dynamic Bounding Volume Hierarchies can be found  [here](https://box2d.org/files/ErinCatto_DynamicBVH_GDC2019.pdf). This details the origin of the cost function and also explains how tree re-balancing works. There are some references at the end of the document that might explain some aspects in more detail.

**Comment by bellpo** [comment]
> eat explanation of Dynamic Bounding Volume Hierarchies can be found [here](https://box2d.org/files/ErinCatto_DynamicBVH_GDC2019.pdf). This details the origin of the cost function and also explains how tree re-balancing works. There are some references at the end of the document that might explain some aspects in more

thank you very much!
