### ISSUE TITLE
Desceptionant

### ISSUE THREAD

**Issue by vicollo128** [lohedges/aabbcc#19]

**Comment by vicollo128** [comment]
i dont see differences

**Comment by lohedges** [comment]
Sorry, I'm not really sure what you're trying to get across. Feel free to re-open if you have an actual question or issue. Minimal working examples and clear descriptions are super helpful.

**Comment by vicollo128** [comment]
Use your library in my simulator, I don't see any difference in performance..

**Comment by lohedges** [comment]
Erm... okay, you chose to open an issue to tell me this? How am I supposed to comment or help if you don't provide any information whatsoever. The following would be helpful:

* What is your simulator? (Do you have example code that I can look at?)
* What collision detection algorithm are you currently using?
* Are you checking overlaps between objects of the same size and shape? (If so, then better algorithms are available.)
* Is your system sparse or dense. (If you have a densely packed system then other algorithms are more efficient.)
* What performance do you expect? (This isn't intended to be a high-performance AABB implementation. Rather it is general, flexible, and (hopefully) easy to use.)

Please don't open issues simply to raise your disappointment, unless you are prepared to back this up with suitable information and working examples. It is of benefit to no-one in the wider community and a waste of my time.
