### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by Ochita** [lohedges/aabbcc#3]
I make lib on mac os x sierra by command make python, then I try to run example from repository and have an error

<Swig Object of type 'std::vector< double > *' at 0x10f81cf48>
Traceback (most recent call last):
  File "aabb_example.py", line 194, in <module>
    treeLarge.insertParticle(i, position, radiusLarge)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Tree_insertParticle'.
  Possible C/C++ prototypes are:
    aabb::Tree::insertParticle(std::vector< double,std::allocator< double > > &,double)
    aabb::Tree::insertParticle(std::vector< double,std::allocator< double > > &,std::vector< double,std::allocator< double > > &)

What im doing wrong? I use python 2.7

**Comment by lohedges** [comment]
Hello there,

Is it possible that you haven't got the latest version of the source files, i.e. AABB.h and AABB.cc? The two method prototypes in the error message look like they are from an older commit:

```cpp
aabb::Tree::insertParticle(std::vector<double>&, double);
aabb::Tree::insertParticle(std::vector<double>&, std::vector<double>&);
```
These should be:

```cpp
aabb::Tree::insertParticle(unsigned int, std::vector<double>&, double);
aabb::Tree::insertParticle(unsigned int, std::vector<double>&, std::vector<double>&);
```

I'd suggest running `git pull` to get the latest version of the repo, then running:

```bash
make clobber
make build
```

Let me know if that works.

Cheers.

**Comment by Ochita** [comment]
Hello. Sorry for opened issue. Seems like strange behavior of my git client - git pull done nothing so I thought that I have last version. After git clone and library rebuilding example code starts to working perfectly. So I can start to test your library on my project. 
Thank you for the quick response and for the good library.

**Comment by lohedges** [comment]
No problem, glad things are working now.
