### ISSUE TITLE
Segfault on querying empty tree.

### ISSUE THREAD

**Issue by joel-simon** [lohedges/aabbcc#4]
How to reproduce on osx python2.7, works fine after addng one element. There is no check in query c++ func for empty tree.
```
import aabb

tree = aabb.Tree(2)
lower, upper = aabb.DoubleVector(2), aabb.DoubleVector(2)
lower[0] = 0
lower[1] = 0
upper[0] = 3
upper[1] = 3
print(list(tree.query(aabb.AABB(lower, upper))))
```

Thanks!

**Comment by lohedges** [comment]
The code now returns an empty vector whenever the tree is empty.

Cheers.
