### ISSUE TITLE
AABB::contains() check is incorrect

### ISSUE THREAD

**Issue by stanleybak** [lohedges/aabbcc#6]
I created an AABB tree with some particles, and then called `updateParticle()` with the same exact data. I expected `updateParticle()` to return `false`, since it shouldn't reinsert the node if it doesn't move. To my surprise, it was always returning `true`. After some debugging, I think there's a mistake in the `AABB::contains()` code. The code is as follows:

```
bool AABB::contains(const AABB& aabb) const
    {
        assert(aabb.lowerBound.size() == lowerBound.size());

        for (unsigned int i=0;i<lowerBound.size();i++)
        {
            if (lowerBound[i] < aabb.lowerBound[i]) return false;
            if (upperBound[i] > aabb.upperBound[i]) return false;
        }

        return true;
    }
```

I believe the check is backwards here. The condition should be switched to `aabb.lowerBound[i] < lowerBound[i])` and `aabb.upperBound[i] > upperBound[i]`. If the current object's lower bound is less than the aabb's lower bound that we're checking against, then it still contains the target aabb. I believe this should greatly improve performance, as right now it seemed to be reinserting particles every time `updateParticle` is called (it may even be incorrect if the AABB grew between updates to contain the original AABB).

**Comment by lohedges** [comment]
Thanks for catching this. The issue should be fixed with the latest commit.

From a quick test, it looks like the example hard disc code is around 25% faster. I imagine that the speedup will probably be greater in situations where there are many slow moving objects, e.g. a computer game.
