### ISSUE TITLE
Usage with volumetric data

### ISSUE THREAD

**Issue by feliwir** [lohedges/aabbcc#7]
Hello,

i am interested in using BVH‘s to space partition volume data. How can i use this library for that use case? I could add the voxels as particles, but i am not sure how effect that‘d be. Any advice?

Thanks

**Comment by lohedges** [comment]
Hello there,

As you say, you could construct AABBs that fully enclosed each voxel and insert them into a tree. Then you could query the tree to determine the neighbours of a specific voxel. (Then use your own algorithms to see if they overlap, or whatever else.) Is this the kind of thing that you are thinking of?

Are your voxels static, or do they change size/shape/position?

**Comment by feliwir** [comment]
Hey, thanks for your quick response. The voxels are all static since i load them from a CT scan. I am thinking about this for raycasting in a volume renderer

**Comment by lohedges** [comment]
Yes, that should work. I belive that others have already adapted this library as part of a [voxel engine](https://github.com/JamesRandall/SimpleVoxelEngine) and combined with ray casting for use in a [platformer](https://github.com/selimanac/DAABBCC).

If you have standard voxel data, then there might be other libraries that are better suited to your needs, e.g. [PolyVox](https://github.com/jvanegmond/polyvox).
